menu:
  - {}
main:
  - name: Home
    url: '#'
    weight: 10
  - name: About Us
    identifier: about
    url: /AB
    weight: 10
  - name: Who We Are
    pageRef: /AB
    parent: about
    weight: 10.5
  - name: Ambassador Tegla Loroupe
    identifier: TL
    parent: about
    pageRef: post/ambassador-tegla-loroupe
    weight: 11
  - name:  Current Projects
    parent: about
    url: /project
    weight: 12
  - name:  Education for Peace
    parent: about
    url: project/new-faculty-at-kapenguria-peace-academy
    weight: 13
  - name:  Partners
    identifier: partners
    parent: about
    url: post/our-partners
    weight: 14
  - name:  North Rift Peace Initiative
    identifier: section-one
    parent: about
    url: /#section-1
    weight: 15
  - name:  Overview
    identifier: overview
    url: /overview
    weight: 20
  - name: Mission
    identifier: mission
    parent: overview
    url: /overview/mission
    weight: 21
  - name: Vision
    identifier: vision
    parent: overview
    url: /overview/vision
    weight: 22
  - name: History
    identifier: history
    parent: overview
    url: /overview/history
    weight: 23
  - name: Foundation Values
    identifier: foundation
    parent: overview
    url: tags/academic/
    weight: 24
  - name: Governance and Management
    identifier: governance
    parent: overview
    url: /overview/governance
    weight: 25
  
  - name: Projects
    identifier: projects
    pageRef: /project
    weight: 30
  - name: Kapenguria Peace Academy Faculty
    identifier: allprojects
    parent: projects
    pageRef: project/new-faculty-at-kapenguria-peace-academy
    weight: 31
  - name: Kakuma Refugee Camp Family Center
    identifier: currentprojects
    parent: projects
    pageRef: project/refugee-camp-family-center
    weight: 32
  - name: Sports Training Center
    identifier: success
    parent: projects
    pageRef: project/the-tegla-loroupe-sports-training-center
    weight: 34
  - name: Peace Academy Dormitory
    parent: projects
    pageRef: project/project-build-new-dormitory-at-kapenguria-school
    weight: 34

  - name: Media Center
    identifier: media_center
    url: /post
    weight: 40
  - name: Newsletters
    identifier: newsletters
    parent: media_center
    pageRef: /post
    weight: 41
  - name: Blog Posts  
    parent: media_center
    pageRef: /blog
    weight: 45
  - name: Gallery
    identifier: gallery
    parent: media_center
    pageRef: /tour
    weight: 46
  - name: Recent Activities
    identifier: recent
    parent: media_center
    pageRef: /event
    weight: 43
  - name: Reports
    identifier: reports
    parent: media_center
    pageRef: /post
    weight: 44
  - name: Slides
    identifier: slides
    parent: media_center
    pageRef: /slides
    weight: 47
  
  - name: Support/Join Us
    identifier: support
    pageRef: /donate
    weight: 50
  - name: Current Project Highlights
    identifier: currenthighlights
    parent: support
    pageRef: /donate
    weight: 51
  - name: Payment Details
    identifier: paymentdetails
    parent: support
    url: /donate/donation-details
    weight: 52
  - name: Contact Us
    identifier: contact
    url: contact/
    weight: 60
  - name: Contact Form
    identifier: contactform
    parent: contact
    url: contact/
    weight: 61
  - name: Map
    identifier: map
    parent: contact
    url: contact/#contact
    weight: 62
  - name: FAQ
    identifier: faq
    parent: contact
    url: contact/
    weight: 63
main_right:
  - name: Courses
    identifier: courses
    url: courses/
    weight: 70
  - name: Tutorial
    identifier: tutorial
    url: Tutorial
    weight: 80
